name: wallet
description: Crypto wallet package for Bitcoin, Ethereum and Tron written in pure Dart.
version: 0.0.12+1
repository: https://github.com/xclud/dart_wallet
homepage: https://github.com/xclud/dart_wallet

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  convert: ^3.1.1
  eip55: ^1.0.2
  pointycastle: ^3.6.2
  sec: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
